@token = a621ef92effc9562459494354b8a6d9b4f9214ec

### Проверить rate limit github по токену и ip

GET https://api.github.com/rate_limit HTTP/1.1
Authorization: token {{token}}
Accept: application/vnd.github.v3+json